(ns zm.header
  "Offsets into the header data structure.")

(def *version           0x0)
(def *flags1            0x1)
(def *himem             0x4)
(def *init-pc           0x6)
(def *dictionary        0x8)
(def *object-table      0xa)
(def *globals           0xc)
(def *static            0xe)
(def *flags2            0x10)
(def *abbreviations     0x18)
(def *file-size         0x1a)
(def *checksum          0x1c)
(def *interp-number     0x1e)
(def *interp-version    0x1f)
(def *height-lines      0x20)
(def *width-chars       0x21)
(def *width-units       0x22)
(def *height-units      0x24)
(def *font-width-units  0x26)
(def *font-height-units 0x27)
(def *routines-offset   0x28)
(def *strings-offset    0x2a)
(def *default-bg        0x2c)
(def *default-fg        0x2d)
(def *standard-revision 0x32)


